spring:
  jpa:
    properties:
      hibernate:
          jdbc:
            lob:
             non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/avaliacaoelotech
    username: postgres
    password: senha10